#!/bin/bash

reset="\[\033[0m\]"
black="${reset}\[\033[30m\]"
red="${reset}\[\033[31m\]"
green="${reset}\[\033[32m\]"
yellow="${reset}\[\033[33m\]"
blue="${reset}\[\033[34m\]"
purple="${reset}\[\033[35m\]"
cyan="${reset}\[\033[36m\]"

__venv_ps1() {
  [ -n "$VIRTUAL_ENV" ] && echo "|${green}$(basename $VIRTUAL_ENV)${reset}| "
}

if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then

  GIT_PS1_SHOWCOLORHINTS=true
  GIT_PS1_SHOWDIRTYSTATE=true
  GIT_PS1_SHOWSTASHSTATE=true
  GIT_PS1_SHOWUNTRACKEDFILES=true
  GIT_PS1_SHOWUPSTREAM="auto"

  . /usr/share/git-core/contrib/completion/git-prompt.sh

  PS1_START="\n${black}(\T) ${blue}\u @ \w${reset} "
  PS1_END="\n→ "

  export PROMPT_COMMAND='__git_ps1 "$PS1_START$(__venv_ps1)" "$PS1_END" "|%s|"'

fi
